[package]
name = "tcp-reverse-proxy-2"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.40", features = ["derive"] }
rustls = "0.23.27"
rustls-pemfile = "2.2.0"
socket2 = "0.5.10"
